#Database connection properties (encrypted)
#Sun Mar 01 00:58:05 GMT+07:00 2026
db.password=ENC\:L11a6ZPUlHG+hJFCD2KNeDPBri2KgbdqVY2rI7E\=
db.url=ENC\:FoIa+b8uweENJQnNGAm5zslvIaVB2+/xdORxHmpjQoD0vtqHPoyuj9xyDH00F2ZRKzSXHI0b4FuKQ7aX9XUPJW7eWck\=
db.user=ENC\:1I2jap0Y0tiK+Kx/rFAYzg8BPSIQf86aBEAeXhAT65swaXBX
